[project]
name = "geo-teacher-llm"
version = "0.1.0"
description = ""
authors = [
    {name = "gvannesson",email = "g.vannesson@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "langchain>=0.3.26,<0.4.0",
    "langchain-openai>=0.3.27,<0.4.0",
    "requests>=2.32.4,<3.0.0",
    "langchain-community (>=0.3.27,<0.4.0)",
    "langchain-ollama (>=0.3.3,<0.4.0)",
    "beautifulsoup4 (>=4.13.4,<5.0.0)",
    "rapidfuzz (>=3.13.0,<4.0.0)",
    "sentence-transformers (>=5.0.0,<6.0.0)",
    "huggingface-hub (>=0.33.2,<0.34.0)",
    "chromadb>=1.0.15",
    "langchain-huggingface>=0.3.0",
    "langchain-chroma>=0.2.4",
    "transformers>=4.53.0",
    "torch>=2.7.1",
    "langdetect>=1.0.9",
    "sentencepiece>=0.2.0",
    "sacremoses>=0.1.1",
    "ruff>=0.12.2",
    "black>=25.1.0",
    "dotenv>=0.9.9",
    "python-dotenv>=1.1.1",
    "pandas>=2.3.0",
    "openpyxl>=3.1.5",
    "langgraph>=0.5.1",
    "ipython>=9.4.0",
    "langsmith>=0.4.4",
    "passlib>=1.7.4",
    "sqlmodel>=0.0.24",
    "psycopg2-binary>=2.9.10",
    "fastapi>=0.116.0",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.35.0",
    "pydantic[email]>=2.11.7",
    "jwt>=1.4.0",
    "django>=5.2.4",
    "unidecode>=1.4.0",
]

[tool.poetry]
name = "geo-teacher-llm"
version = "0.1.0"
description = ""
authors = ["Ton Nom <ton.email@example.com>"]

packages = [
  { include = "geo_teacher_llm" }
]

[tool.black]
line-length = 88
target-version = ["py312"]
exclude = '''
/(
    \.venv
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["build", "dist", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"] # si tu souhaites ignorer la limite de ligne

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
