[project]
name = "geo-teacher-llm"
version = "0.1.0"
description = ""
authors = [
    {name = "gvannesson",email = "g.vannesson@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "langchain (>=0.3.26,<0.4.0)",
    "langchain-openai (>=0.3.27,<0.4.0)",
    "requests (>=2.32.4,<3.0.0)",
    "langchain-community (>=0.3.27,<0.4.0)",
    "langchain-ollama (>=0.3.3,<0.4.0)",
    "beautifulsoup4 (>=4.13.4,<5.0.0)",
    "rapidfuzz (>=3.13.0,<4.0.0)",
    "sentence-transformers (>=5.0.0,<6.0.0)",
    "huggingface-hub (>=0.33.2,<0.34.0)",
    "chromadb>=1.0.15",
    "langchain-huggingface>=0.3.0",
    "langchain-chroma>=0.2.4",
    "transformers>=4.53.0",
    "torch>=2.7.1",
    "langdetect>=1.0.9",
    "sentencepiece>=0.2.0",
    "sacremoses>=0.1.1",
]

[tool.poetry]
name = "geo-teacher-llm"
version = "0.1.0"
description = ""
authors = ["Ton Nom <ton.email@example.com>"]

packages = [
  { include = "geo_teacher_llm" }
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
