name: CI

on:
  push:
    branches: [ main, geo_llm ]
  pull_request:
    branches: [ main, geo_llm ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Create uv virtual environment
        run: uv venv

      - name: Install dependencies
        # run: uv pip install -r requirements.txt  # si tu as requirements.txt
        # # ou
        run: uv pip install .  # si ton pyproject.toml est prêt à s'installer

      - name: Run Ruff
        run: uv run ruff check geo_teacher_llm

      - name: Run Black
        run: uv run black --check geo_teacher_llm
